### PR TITLE
Do not require service configuration

### PR DESCRIPTION
**Pull request by krhubert**

### CODE REVIEW

**Comment by antho1404** [comment]
Why is this a hight priority? I don't understand what problem does it solve. Please provide details of the reason of this change

**Comment by krhubert** [comment]
```
./bin/run service:dev ../test-service
Create service... !
Error: 2 UNKNOWN: Service.Configuration is a required field
```

for given mesg.yaml.

```
name: "test-service"
events:
  foo:
    data:
      bar:
        type: String
```

So, the configuration could be left empty.

**Comment by antho1404** [comment]
ok, nice catch.

The validation on the data should stay and the creation of the default config should not be on the validation but on the creation of the resource.

Just move this
```
if srv.Configuration == nil {
  srv.Configuration = &service.Dependency{}
}
```
to `sdk/service.go#Create` and that should be the only modification needed

**Comment by antho1404** [comment]
I created another PR that can replace this one https://github.com/mesg-foundation/engine/pull/1165

**Pull request closed without merging**
