### PR TITLE
Lint protobuf definitions

### PR DESCRIPTION
**Pull request by antho1404**
fix https://github.com/mesg-foundation/engine/issues/1408

This is more like experimentation to discuss if we want to lint the proto based on https://buf.build/

TODO:

- [x] suffix all services with `Service`
- [x] UPPERCASE for enums
- [x] no camelCase for attributes
- [x] no response/stream with a type
- [x] package version
- [x] normalization messages `XXServiceMethodName[Request|Response]`
- [x] enum with UNSPECIFIED instead of UNKNOWN

List of things to fix more
```
protobuf/api/account.proto:6:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/event.proto:7:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/execution.proto:7:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/instance.proto:6:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/ownership.proto:6:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/process.proto:6:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/api/service.proto:6:1:Files with package "mesg.api.v1" must be within a directory "mesg/api/v1" relative to root but were in directory "protobuf/api".
protobuf/types/account.proto:5:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/account.proto:5:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/account.proto:6:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/event.proto:6:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/event.proto:6:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/event.proto:7:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/execution.proto:6:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/execution.proto:6:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/execution.proto:7:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/instance.proto:5:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/instance.proto:5:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/instance.proto:6:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/ownership.proto:5:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/ownership.proto:5:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/ownership.proto:6:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/process.proto:6:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/process.proto:6:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/process.proto:7:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
protobuf/types/service.proto:5:1:Multiple packages "mesg.protobuf,mesg.types.v1" detected within directory "protobuf/types".
protobuf/types/service.proto:5:1:Files with package "mesg.types.v1" must be within a directory "mesg/types/v1" relative to root but were in directory "protobuf/types".
protobuf/types/service.proto:6:1:Files in package "mesg.types.v1" have multiple values "github.com/mesg-foundation/engine/account,github.com/mesg-foundation/engine/event,github.com/mesg-foundation/engine/execution,github.com/mesg-foundation/engine/instance,github.com/mesg-foundation/engine/ownership,github.com/mesg-foundation/engine/process,github.com/mesg-foundation/engine/service" for option "go_package" and all values must be equal.
```

### CODE REVIEW

**Comment by krhubert** [comment]
So I like the idea of having linter, 

Now things I don't like:

- message versioning - we are not in the beta stage so let's not slow us down with versioning. We can add them before beta release
- `ServiceService` looks awful and I don't see the point of repeating that prefix (just to satisfy linter...). I know that you want to prefix service etc, but do we really need that?
- enum name (mix of camel case and the upper case looks wired)

otherwise LGTM

**Comment by bufdev** [comment]
Happy to provide any help here - I'd recommend adding a `buf.yaml` to the root of your repository to manage this. Also see https://github.com/bufbuild/buf-example for a full example for CI - we can add a CircleCI build if you'd like as an example.

**Comment by bufdev** [comment]
I added a CircleCI example to https://github.com/bufbuild/buf-example - it does look like you are very proficient in CircleCI, however, so you probably don't need this help :-)

**Comment by NicolasMahe** [comment]
closing because this PR is too old and is referenced in issue https://github.com/mesg-foundation/engine/issues/1408

**Pull request closed without merging**
