### PR TITLE
[WIP] Service single output -  update importer package

### PR DESCRIPTION
**Pull request by krhubert**
Change importer outputs to parameter

### CODE REVIEW

**Comment by NicolasMahe** [comment]
@krhubert please divide your work in multiple PRs following the step in https://forum.mesg.com/t/simplification-of-the-tasks-output/265/6.

The first PR should be about only updating the importer package. basically commit https://github.com/mesg-foundation/core/pull/962/commits/97841148312d821f21dc5faa052a9639a1acecde and https://github.com/mesg-foundation/core/pull/962/commits/6d436e281893fb8957390e6f9cbb047455095a44 + transform the new outputs to to multiple output for service definition (current service definition).
This way, only the importer package have to be updated and the rest of the codebase doesn’t.

**Comment by krhubert** [comment]
I know but I prefer to do all the work then split it. That way I know what needs to be done. It's easier for me that way.

**Comment by antho1404** [comment]
> There is no way for updating only importer package because you have to update api (63043d7) 

You can simply add one input to the list of outputs without changing the structure

defOutputsToService will become something like that:
```go
return []*service.Output{
  &service.Output{Key: "success", Data: defParametersToService(outputs)}
}
```

this way the internal structure doesn't change only the importer changes

**Comment by NicolasMahe** [comment]
> > There is no way for updating only importer package because you have to update api ([63043d7](https://github.com/mesg-foundation/core/commit/63043d7b761abec346a87446becc432671d7d492))
> 
> You can simply add one input to the list of outputs without changing the structure
> 
> defOutputsToService will become something like that:
> 
> ```go
> return []*service.Output{
>   &service.Output{Key: "success", Data: defParametersToService(outputs)}
> }
> ```
> 
> this way the internal structure doesn't change only the importer changes

let's not forget error output ;)

something like:
```go
return []*service.Output{
  &service.Output{Key: "success", Data: defParametersToService(outputs)},
  &service.Output{Key: "error", Data: DATA} // see forum topic
}
```

**Comment by NicolasMahe** [comment]
@krhubert can you close this PR and remove the branch since you open new ones

**Comment by NicolasMahe** [comment]
@krhubert can you close this PR and remove the branch since you open new ones

**Pull request closed without merging**
