### PR TITLE
Test/e2e processes

### PR DESCRIPTION
**Pull request by krhubert**
dep: https://github.com/mesg-foundation/engine/pull/1500

Start e2e process simple test, but got a panic:

```
panic: not implemented

goroutine 2260 [running]:
github.com/mesg-foundation/engine/process.(*Process_Node).ID(0xc0041c7410, 0x44796c, 0x0)
	/root/go/src/github.com/mesg-foundation/engine/process/process.go:26 +0x221
github.com/mesg-foundation/engine/process.Process.FindNode.func1(0xc0041c7410, 0x0)
	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:39 +0x3d
github.com/mesg-foundation/engine/process.Process.FindNodes(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:29 +0xb5
github.com/mesg-foundation/engine/process.Process.FindNode(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:38 +0xb3
github.com/mesg-foundation/engine/process.Process.validate(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:154 +0xd1
github.com/mesg-foundation/engine/process.(*Process).Validate(0xc003df3880, 0xc003e29ee0, 0x20)
	/root/go/src/github.com/mesg-foundation/engine/process/process.go:34 +0xed
...
```

Need to debug more what's going on, because I'm not sure why it happens.

### CODE REVIEW

**Comment by NicolasMahe** [comment]
> Start e2e process simple test, but got a panic:
> 
> ```
> panic: not implemented
> 
> goroutine 2260 [running]:
> github.com/mesg-foundation/engine/process.(*Process_Node).ID(0xc0041c7410, 0x44796c, 0x0)
> 	/root/go/src/github.com/mesg-foundation/engine/process/process.go:26 +0x221
> github.com/mesg-foundation/engine/process.Process.FindNode.func1(0xc0041c7410, 0x0)
> 	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:39 +0x3d
> github.com/mesg-foundation/engine/process.Process.FindNodes(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
> 	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:29 +0xb5
> github.com/mesg-foundation/engine/process.Process.FindNode(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
> 	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:38 +0xb3
> github.com/mesg-foundation/engine/process.Process.validate(0xc003e29ee0, 0x20, 0x20, 0xc003e2dee0, 0xc, 0xc003e1cda0, 0x2, 0x2, 0xc00002fab0, 0x1, ...)
> 	/root/go/src/github.com/mesg-foundation/engine/process/graph.go:154 +0xd1
> github.com/mesg-foundation/engine/process.(*Process).Validate(0xc003df3880, 0xc003e29ee0, 0x20)
> 	/root/go/src/github.com/mesg-foundation/engine/process/process.go:34 +0xed
> ...
> ```
> 
> Need to debug more what's going on, because I'm not sure why it happens.

I don't think you can directly convert the JSON to the go protobuf message. If I remember correctly, JS is convert the JSON to protobuf not the same way that Go. I'm not sure if it something special in the CLI or just the JS proto lib.
To check, create a simple process in Go (directly `CreateProcessRequest`) and marshal it in JSON.

**Comment by krhubert** [comment]
Can we merge this?

**Comment by NicolasMahe** [comment]
> Can we merge this?

Let first merge #1500 as it is dependent.

**Comment by antho1404** [comment]
@krhubert can you fix the conflicts in order to merge the PR

**Pull request merged**
